name: qlinica_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  http: ^1.2.0
  shared_preferences: ^2.3.2
  local_auth: ^2.3.0
  get: ^4.7.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon_blue.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A7A8A"
  adaptive_icon_foreground: "assets/images/app_icon_blue.png"
  web:
    generate: false

flutter_native_splash:
  color: "#1E3A8A"
  image: assets/images/app_icon_white_padded.png
  android_12:
    color: "#1E3A8A"
    image: assets/images/app_icon_white_padded.png
  fullscreen: false
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
